---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    #theme: cerulean
---

# Plotly

We'are making interactive plots.

```{r}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```


Focus on NYC Airbnb data.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Let's make a scatterplot!

```{r}
nyc_airbnb |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    type = "scatter", mode = "markers", alpha = 0.5)

nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |>
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5)
```

Let's make a box plot!

```{r}
nyc_airbnb |>
  plot_ly(y = ~price, color = ~neighbourhood, type = "box")

nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

Let's make a bar plot!

```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar")

nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |>
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood,
          type = "bar", colors = "viridis")
```
